version: '3.7'

services:
  app:
    image: gilgammesh/app-vuelos:v2
    container_name: app-vuelos
    env_file:
      - .env
    ports:
      - 80:4000
    depends_on:
      - rabbitmq
      - mongodb
    restart: always
    networks:
      - ms_nestjs
  
  ms-flights:
    image: gilgammesh/ms-flights:v2
    container_name: ms-flights
    env_file:
      - .env
    depends_on:
      - rabbitmq
      - mongodb
    restart: always
    networks:
      - ms_nestjs
  
  ms-passengers:
    image: gilgammesh/ms-passengers:v2
    container_name: ms-passengers
    env_file:
      - .env
    depends_on:
      - rabbitmq
      - mongodb
    restart: always
    networks:
      - ms_nestjs
  
  ms-users:
    image: gilgammesh/ms-users:v2
    container_name: ms-users
    env_file:
      - .env
    depends_on:
      - rabbitmq
      - mongodb
    restart: always
    networks:
      - ms_nestjs

  rabbitmq:
    image: rabbitmq:3.9-management
    container_name: rabbitmq
    expose:
      - 5672
      - 15672
    restart: always
    networks:
      - ms_nestjs
  
  mongodb:
    image: mongo:6
    container_name: mongodb
    ports:
      - 27019:27017
    environment:
      - MONGODB_DATABASE=superFlights
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - mongodb:/data/db
    expose:
      - 27019
    restart: always
    networks:
      - ms_nestjs

volumes:
  mongodb:

networks:
  ms_nestjs: